/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        jade: {
          50: 'var(--jade-50)',
          100: 'var(--jade-100)',
          150: 'var(--jade-150)',
          175: 'var(--jade-175)',
          200: 'var(--jade-200)',
          225: 'var(--jade-225)',
          300: 'var(--jade-300)',
          400: 'var(--jade-400)',
          bright: 'var(--jade-bright)',
          600: 'var(--jade-600)',
          800: 'var(--jade-800)',
          900: 'var(--jade-900)',
          950: 'var(--jade-950)',
          DEFAULT: 'var(--jade-600)',
        },
        amber: {
          100: 'var(--amber-100)',
          500: 'var(--amber-500)',
          800: 'var(--amber-800)',
        },
        ink: {
          900: 'var(--ink-900)',
          700: 'var(--ink-700)',
          500: 'var(--ink-500)',
          400: 'var(--ink-400)',
          300: 'var(--ink-300)',
          DEFAULT: 'var(--ink-900)',
        },
        paper: 'var(--paper)',
        page: 'var(--page)',
        hover: 'var(--hover)',
        white: 'var(--white)',
        line: {
          DEFAULT: 'var(--line)',
          soft: 'var(--line-soft)',
          track: 'var(--line-track)',
        },
        danger: 'var(--danger)',
        warning: 'var(--warning)',
        info: 'var(--info)',
        scrim: 'var(--scrim)',
        // Legacy aliases for untouched screens
        mist: 'var(--mist)',
        lacquer: 'var(--lacquer)',
      },
      fontFamily: {
        sans: ['Manrope', '"Noto Sans Myanmar"', 'system-ui', 'sans-serif'],
        display: [
          '"Bricolage Grotesque"',
          '"Noto Sans Myanmar"',
          'system-ui',
          'sans-serif',
        ],
        myanmar: ['"Noto Sans Myanmar"', 'Manrope', 'system-ui', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '32px',
        '3xl': '48px',
        '4xl': '64px',
        '5xl': '96px',
      },
      borderRadius: {
        sm: '8px',
        '2sm': '10px',
        md: '12px',
        '2md': '14px',
        lg: '16px',
        bubble: '18px',
        xl2: '20px',
        '2xl': '22px',
        xl: '24px',
        sheet: '26px',
        full: '999px',
      },
      boxShadow: {
        sm: '0 1px 2px rgba(16,22,19,0.05)',
        md: '0 1px 2px rgba(16,22,19,0.04), 0 8px 26px rgba(16,22,19,0.05)',
        lg: '0 30px 80px rgba(16,22,19,0.24)',
        cta: '0 4px 14px rgba(14,130,86,0.28)',
        focus: '0 0 0 3px rgba(14,130,86,0.20)',
      },
      maxWidth: {
        container: '1180px',
        hero: '560px',
        conversation: '620px',
        brief: '680px',
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.2, 0, 0, 1)',
      },
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '260ms',
      },
      lineHeight: {
        burmese: '1.8',
      },
    },
  },
  plugins: [],
};
